"""Initial Migration

Revision ID: 4ded79321eb9
Revises: 6d6ea6f5476c
Create Date: 2021-04-27 07:42:48.710932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ded79321eb9'
down_revision = '6d6ea6f5476c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'time')
    # ### end Alembic commands ###
